// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP6x0DR-U5cI6B4BmyPHSMZDupOBMPsqM',
    appId: '1:459452418965:web:15e12846a14cfac2b1449c',
    messagingSenderId: '459452418965',
    projectId: 'portfolio-e7e14',
    authDomain: 'portfolio-e7e14.firebaseapp.com',
    storageBucket: 'portfolio-e7e14.firebasestorage.app',
    measurementId: 'G-C4D0HLB21H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM5JDCgc6sMnwMop1HXHseBo0q-WIMl9k',
    appId: '1:459452418965:android:2d48f43d10f4b69cb1449c',
    messagingSenderId: '459452418965',
    projectId: 'portfolio-e7e14',
    storageBucket: 'portfolio-e7e14.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP6x0DR-U5cI6B4BmyPHSMZDupOBMPsqM',
    appId: '1:459452418965:web:65efa5e380987002b1449c',
    messagingSenderId: '459452418965',
    projectId: 'portfolio-e7e14',
    authDomain: 'portfolio-e7e14.firebaseapp.com',
    storageBucket: 'portfolio-e7e14.firebasestorage.app',
    measurementId: 'G-3RK7EYHBEG',
  );
}
